
/*Roles*/
INSERT INTO role(name) VALUES('ROLE_USER');
INSERT INTO role(name) VALUES('ROLE_ADMIN');

/*Row*/
INSERT INTO bow (id, number_arrows, name, damage, description, img, available) VALUES (1, 1, 'Arco ancestral', 44, 'Arco elaborado con tecnología sheikah gracias a la investigación de Rotver. Dispara flechas que describen una trayectoria recta.', 'https://vignette.wikia.nocookie.net/zelda/images/a/a6/Ancient-bow.png/revision/latest/scale-to-width-down/65?cb=20180705172306&path-prefix=es', true);
INSERT INTO bow (id, number_arrows, name, damage, description, img, available) VALUES (2, 3, 'Arco bestial', 20, 'Arco de centaleón con estructura reforzada. La cuerda también es metálica, por lo que a los hylianos de a pie les cuesta utilizarlo.', 'https://vignette.wikia.nocookie.net/zelda/images/8/85/Arco_bestial.png/revision/latest/scale-to-width-down/65?cb=20180705175409&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (3, 4, 'Arco boko', 4, 'Arco sencillo que emplean los bokoblin. Está elaborado con la primera rama y cuerda que tienen a la mano, por lo que no cabe esperar de él una gran potencia de disparo.', 'https://vignette.wikia.nocookie.net/zelda/images/1/1e/Arco_Boko_BotW.png/revision/latest/scale-to-width-down/65?cb=20170306134529&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (4, 24, 'Arco boko de dragón', 24, 'Arco boko reforzado por medio de huesos de fósil. Elaborado con materiales elegidos cuidadosamente por los bokoblin, que le ofrecen gran potencia de disparo.', 'https://vignette.wikia.nocookie.net/zelda/images/f/ff/Arco_boko_de_drag%C3%B3n.png/revision/latest/scale-to-width-down/65?cb=20180705173933&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (5, 12, 'Arco boko punzante', 12, 'Parece endeble, pero esta versión mejorada del arco boko incluye huesos de animales que aumentan la potencia de disparo y la resistencia. Es ligero y fácil de usar.', 'https://vignette.wikia.nocookie.net/zelda/images/8/87/Arco_boko_punzante_BotW.png/revision/latest/scale-to-width-down/65?cb=20170327000800&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (6, 3, 'Arco colosal', 32, 'Arco de centaleón elaborado con un metal extraído de la Montaña de la Muerte. Su potencia de disparo es brutal; puede atravesar una armadura como si fuera papel.', 'https://vignette.wikia.nocookie.net/zelda/images/5/5c/Arco_colosal.png/revision/latest/scale-to-width-down/65?cb=20180705192843&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (7, 3, 'Arco de águila', 28, 'Arco único que utilizaba Revali, el elegido orni. Se dice que disparaba a velocidad de vértigo, y que no tenía rival en combates aéreos.', 'https://vignette.wikia.nocookie.net/zelda/images/e/e1/Arco_de_%C3%A1guila.png/revision/latest/scale-to-width-down/65?cb=20180705233604&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (8, 1, 'Arco de caballero', 26, 'Arco que utilizaban los caballeros del castillo de Hyrule. Su acabado metálico le otorga resistencia y precisión.', 'https://vignette.wikia.nocookie.net/zelda/images/5/5f/Arco_de_caballero_BotW.png/revision/latest/scale-to-width-down/65?cb=20180417184617&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (9, 3, 'Arco de centaleón', 10, 'Arco de centaleón elaborado a partir de metal sin refinar. Capaz de disparar varias flechas en abanico, su gran rango de alcance es útil frente a enemigos veloces.', 'https://vignette.wikia.nocookie.net/zelda/images/0/0c/Arco_de_centale%C3%B3n.png/revision/latest/scale-to-width-down/65?cb=20180705235356&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (10, 1,  'Arco de madera', 4, 'Sencillo arco de madera fabricado para cazar animales pequeños. No se considera apto para luchar contra monstruos.', 'https://vignette.wikia.nocookie.net/zelda/images/0/07/Arco_de_madera_BotW.png/revision/latest/scale-to-width-down/65?cb=20170320144450&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (11, 1,  'Arco de golondrina', 9, 'Arco muy común entre los orni. Su cuerda se ha diseñado especialmente para combates aéreos, por lo que resulta más fácil de sacar del carcaj que un arco normal.', 'https://vignette.wikia.nocookie.net/zelda/images/5/5e/Arco_de_golondrina_BotW.png/revision/latest/scale-to-width-down/65?cb=20170621114336&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (12, 1,  'Arco de halcón', 20, 'Exquisito arco elaborado por un maestro arquero orni. Dispara más rapido que un arco normal, por lo que suelen usarlo los guerreros más diestros en combate aéreo.', 'https://vignette.wikia.nocookie.net/zelda/images/c/ce/Arco_de_halc%C3%B3n.png/revision/latest/scale-to-width-down/65?cb=20180706001327&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (13, 1,  'Arco de viajero', 5, 'Arco pequeño que los viajeros usan para defenderse. Las flechas ayudan a acertar a enemigos que se encuentran lejos.', 'https://vignette.wikia.nocookie.net/zelda/images/f/fc/Arco_de_viajero_BotW.png/revision/latest/scale-to-width-down/65?cb=20170306134549&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (14, 1,  'Arco de soldado', 14, 'Arco mejorado expresamente para el combate. Inflige más daño, pero arde si entra en contacto con el fuego.', 'https://vignette.wikia.nocookie.net/zelda/images/1/10/Arco_de_soldado_BotW.png/revision/latest/scale-to-width-down/65?cb=20170325160642&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (15, 3,  'Arco del bosque', 15, 'Arco kolog diseñado para hylianos, capaz de disparar varias flechas a la vez. La cuerda se ha elaborado con hierba, mientras que la estructura es de madera flexible.', 'https://vignette.wikia.nocookie.net/zelda/images/4/4d/Arco_del_bosque_BotW.png/revision/latest/scale-to-width-down/65?cb=20170320154826&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (16, 1,  'Arco del Crepúsculo', 30, 'Arco que empleó la princesa que combatió junto al héroe los monstruos del crepúsculo. Dispara flechas rectas y certeras como rayos gracias al poder de luz que alberga.', 'https://vignette.wikia.nocookie.net/zelda/images/7/7e/Sprite_Arco_del_crep%C3%BAsculo.png/revision/latest/scale-to-width-down/65?cb=20170326190651&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (17, 1,  'Arco del vigilante', 10, 'Arco que ha pasado de generación en generación entre los sheikah. Se dice que concentrarse antes de tensarlo sirve para alcanzar a enemigos lejanos con precisión.', 'https://vignette.wikia.nocookie.net/zelda/images/9/9c/Arco_del_vigilante.png/revision/latest/scale-to-width-down/65?cb=20180706001750&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (18, 1,  'Arco de la guardia', 50, 'Arco elaborado por los sheikah para acabar con el cataclismo. Destaca por su elevada potencia y cadencia de disparo, aunque en detrimento de la resistencia.', 'https://vignette.wikia.nocookie.net/zelda/images/a/a2/Arco_de_la_guardia.png/revision/latest/scale-to-width-down/65?cb=20180706001935&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (19, 1,  'Arco de Luz', 100, 'Arma que te dio Zelda antes de la batalla decisiva contra Ganon. Cuando el héroe lo usa, acumula luz y dispara flechas capaces de acabar con el cataclismo.', 'https://vignette.wikia.nocookie.net/zelda/images/b/bc/Arco_de_luz_BotW.png/revision/latest/scale-to-width-down/65?cb=20170325141335&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (20, 2, 'Arco doble', 14, 'Arco empleado por los arqueros más diestros del clan Yiga. Está diseñado para disparar dos flechas a la vez, lo que suele acabar con todo lo que se le pone por delante.', 'https://vignette.wikia.nocookie.net/zelda/images/3/3a/Arco_doble.png/revision/latest/scale-to-width-down/65?cb=20180706002208&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (21, 1, 'Arco gerudo', 14, 'Arco de la tribu gerudo que destaca por sus elaborados adornos. Su gran alcance lo convierte en el aliado perfecto tanto en el combate como para la caza en el desierto.', 'https://vignette.wikia.nocookie.net/zelda/images/6/69/Arco_gerudo.png/revision/latest/scale-to-width-down/65?cb=20180706002301&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (22, 1, 'Arco lizal', 14, 'Arco de madera fabricado por lizalfos y reforzado con espinas de un gran pez. Su potencia de ataque es superior a la de un arco de madera sencillo.', 'https://vignette.wikia.nocookie.net/zelda/images/3/30/Arco_lizal.png/revision/latest/scale-to-width-down/65?cb=20180706002426&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (23, 1, 'Arco lizal de acero', 36, 'Arco usado únicamente por los más diestros arqueros lizalfos. Su estructura reforzada con acero le confiere más peso, aunque al mismo tiempo lo hace más duradero.', 'https://vignette.wikia.nocookie.net/zelda/images/4/47/Arco_lizal_de_acero.png/revision/latest/scale-to-width-down/65?cb=20180706002706&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (24, 1, 'Arco lizal reforzado', 25, 'Arco lizal reforzado con metal. La madera flexible de árboles ribereños con la que está elaborada su estructura le aporta una potencia de disparo nada desdeñable.', 'https://vignette.wikia.nocookie.net/zelda/images/a/a3/Arco_lizal_reforzado.png/revision/latest/scale-to-width-down/65?cb=20180706002600&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (25, 1, 'Arco real', 38, 'Arco que el rey de Hyrule entregaba a los caballeros más diestros con dicha arma. Destaca por su original diseño y por su excelente capacidad de disparo.', 'https://vignette.wikia.nocookie.net/zelda/images/9/9a/Arco_real.png/revision/latest/scale-to-width-down/65?cb=20180706002855&path-prefix=es', true);
INSERT INTO bow (id, number_arrows,  name, damage, description, img, available) VALUES (26, 1, 'Arco zora', 15, 'Arco empleado por los zora para pescar, entre otros menesteres. No posee una gran potencia de disparo, pero el metal con el que esta fabricado lo hace muy resistente.', 'https://vignette.wikia.nocookie.net/zelda/images/f/fb/Arco_zora_BotW.png/revision/latest/scale-to-width-down/65?cb=20180423003947&path-prefix=es', true);